# Generated by Django 4.2.6 on 2023-12-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_AB_m',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_AB_plus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_A_m',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_A_plus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_B_m',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_B_plus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_O_m',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_O_plus',
            field=models.IntegerField(default=0),
        ),
    ]
