# Generated by Django 4.2.6 on 2023-12-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_remove_order_quantity_order_quantity_ab_m_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('En Attente', 'En Attente'), ('Confirmée', 'Confirmée'),
                                            ('Délivrée', 'Délivrée'), ('Annulée', 'Annulée')], default=('En Attente', 'En Attente'), max_length=50),
        ),
    ]
