# Generated by Django 4.2.5 on 2023-12-24 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_donor_email_donor_phone_alter_donor_blood_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reactant',
        ),
    ]
