# Generated by Django 4.2.5 on 2023-12-23 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_order_status'),
        ('apps', '0003_rename_anti_htlv2_test_analysis_anti_hlv2_test'),
    ]

    operations = [
    ]
