# Generated by Django 4.2.5 on 2023-11-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_remove_medication_donor_remove_surgery_donor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='status',
            field=models.CharField(blank=True, choices=[('Eligible', 'Eligible'), ('En Attente de Confirmation', 'Attente'), ('Ineligible', 'Ineligible')], default=('En Attente de Confirmation', 'Attente'), max_length=255, null=True),
        ),
    ]
