# Generated by Django 4.2.5 on 2023-12-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_users_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Client', 'Client'), ('Docteur', 'Docteur'), ('gcc', 'Gestionnaire'), ('Laborantin', 'Laborantin'), ('Infirmier(e)', 'Infirmier(e)')], max_length=20, null=True),
        ),
    ]
