# Generated by Django 4.2.5 on 2023-12-23 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_merge_20231223_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='psl',
            name='dispo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='psl',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.order'),
        ),
    ]
