# Generated by Django 4.2.7 on 2023-12-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_donor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='adress',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
