# Generated by Django 4.2.5 on 2023-12-24 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_psl_dispo_psl_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psl',
            name='order',
        ),
    ]
