# Generated by Django 4.2.7 on 2023-12-10 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_client_adress_client_email_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='psl',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.order'),
        ),
        migrations.AlterField(
            model_name='psl',
            name='serial',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='psl',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
