# Generated by Django 4.2.5 on 2023-12-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
