# Generated by Django 4.2.7 on 2023-12-11 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_order_quantity_psl_order_alter_psl_serial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='adress',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='location',
            name='stock',
        ),
        migrations.AddField(
            model_name='location',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.stock'),
        ),
    ]
