# Generated by Django 4.2.5 on 2023-12-13 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_alter_client_adress_alter_client_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='type',
            new_name='typ',
        ),
    ]
