# Generated by Django 4.2.5 on 2023-12-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_rename_type_analysis_typ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood',
            name='volume',
            field=models.IntegerField(choices=[('350', '350'), ('400', '400'), ('450', '450'), ('500', '500')]),
        ),
    ]
