# Generated by Django 4.2.6 on 2024-02-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_alter_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O-', 'O-'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-')], max_length=50, null=True),
        ),
    ]
