# Generated by Django 4.2.5 on 2023-12-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_alter_blood_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood',
            name='state',
            field=models.CharField(choices=[('Eligible', 'Eligible'), ('Ineligible', 'Ineligible'), ('Attente', 'Analyse en Cours')], default=('Attente', 'Analyse en Cours'), max_length=255),
        ),
        migrations.AlterField(
            model_name='blood',
            name='volume',
            field=models.FloatField(choices=[(350, 350), (400, 400), (450, 450), (500, 500)], default=(450, 450)),
        ),
    ]
