# Generated by Django 4.2.6 on 2024-05-18 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_donor_password_donor_username_users_donor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('date_to_be', models.DateTimeField()),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('A', 'accepted'), ('P', 'pending'), ('R', 'refused')], default='P', max_length=1)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='appointements', related_query_name='appointment', to='apps.donor')),
            ],
        ),
    ]
