# Generated by Django 4.2.6 on 2024-05-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_to_be',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
